#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'open-uri'
  gem 'json'
  gem 'time'
  gem 'nokogiri'
end

require 'open-uri'
require 'nokogiri'
require 'json'
require 'time'

url = 'https://www.zonneplan.nl/energie/dynamische-energieprijzen'
dat_file = 'build/hours.dat'
bitmap_file = 'build/hours.png'
url_options = {
  "User-Agent" => "Ruby/#{RUBY_VERSION}; Leon Berenschot; https://github.com/LeipeLeon/zonneplan"
}

html = URI.open(url, url_options).read
doc = Nokogiri::HTML(html)

ENV['TZ'] = 'Europe/Amsterdam'

Dir.mkdir('build') unless Dir.exist?('build')

def generate_data_file(hours, dat_file)
  colors = {
    "stale" => "0xCCCCCC",
    "low" => "0x999999",
    "normal" => "0x666666",
    "high" => "0x000000",
  }

  File.open(dat_file, 'w') do |f|
    now = Time.now.localtime
    graph_hours = hours.reverse.reject { (Time.parse(_1['dateTime']).localtime - now) < -3600 * 4 } # skip prices older than 4 hours
    upcoming_hours = hours.reverse.reject { (Time.parse(_1['dateTime']).localtime - now) < -3600 } # skip prices older than 1 hour
    prices = upcoming_hours.map { _1['priceTotalTaxIncluded']}
    min_price = (prices.min.to_f / 100000).round(1)
    max_price = (prices.max.to_f / 100000).round(1)
    graph_hours.each do |item|
      price_date = Time.parse(item['dateTime']).localtime
      day_hour = price_date.strftime('%H')
      price = (item['priceTotalTaxIncluded'].to_f / 100000).round(1)
      color = now - 3600 > price_date ? colors['stale'] : colors[item['pricingProfile']]
      boudary_price = price if (min_price == price || max_price == price) if (price_date - now ) > -3600
      f.puts "#{day_hour} #{price} #{color} #{boudary_price}"
    end

    puts "Data successfully written to #{dat_file}."
  end
end

def execute_gnuplot(dat_file, bitmap_file, title)
  gnuplot_script = <<~SCRIPT
    set terminal pngcairo size 800,600 enhanced font 'Verdana,10'
    # set title 'Zonneplan Dynamische Energieprijzen'
    # set xlabel 'Hour of the Day'
    # set ylabel 'Price (EUR/kWh)'
    # set grid
    # set style fill solid 0.5
    set term pngcairo size 800,460 enhanced font 'Verdana,10'
    set output "#{bitmap_file}"

    set key autotitle columnhead
    unset key

    set title "#{title}"
    set xlabel "Hour of the Day"
    set ylabel "Price (EUR/kWh)"

    set nokey
    set border 1+2
    set boxwidth 0.8
    set style fill solid
    set xtics font ",10"

    set xtics nomirror
    set ytics nomirror

    # set yrange [0:7]
    set grid y
    # set ylabel "Price €"

    plot '#{dat_file}' using 0:2:3:xtic(1) with boxes lc rgb var, '' using 0:2:4 with labels offset 0,1

  SCRIPT

  File.write('build/plot.gp', gnuplot_script)

  system('gnuplot build/plot.gp')
  puts "Plot generated as build/hours.png."
end

if (next_data_json = doc.at_css('script#__NEXT_DATA__'))
  data = JSON.parse(next_data_json.text)

  if (hours = data.dig('props', 'pageProps', 'data', 'templateProps', 'energyData', 'electricity', 'hours'))
    # title = "Zonneplan #{DateTime.parse(hours[0]['dateTime']).strftime('%d-%m-%Y')} #{Time.now.localtime.strftime("%H:%M")}"
    title = "Zonneplan #{Time.now.localtime.strftime("%d-%m-%Y %H:%M")}"
    generate_data_file(hours, dat_file)
    execute_gnuplot(dat_file, bitmap_file, title)
    system("magick #{bitmap_file} -dither FloydSteinberg -define dither:diffusion-amount=50% -ordered-dither h4x4a build/dithered.png")
    system("magick build/dithered.png -monochrome -colors 2 -depth 1 -strip png:build/diffused.png")
    system("magick build/dithered.png -monochrome -colors 2 -depth 1 -strip bmp3:build/diffused.bmp")
  else
    throw "No electricity hours data found in __NEXT_DATA__."
  end
else
  throw "Script tag with id='__NEXT_DATA__' not found."
end
