#!/usr/bin/env bash

mkdir -p build
# fetch latest version
docker pull ghcr.io/leipeleon/chrome-headless-screenshots:master

# # Screenshot whole page and crop out the graph
# docker run -v $(pwd):/usr/src/app/out --rm ghcr.io/leipeleon/chrome-headless-screenshots:master https://www.zonneplan.nl/energie/dynamische-energieprijzen --height 2160 --filename "build/screenshot" --timezone "Europe/Amsterdam"
# magick build/screenshot.png -chop 390x520 -crop 1135x681 build/cropped.png
# magick build/cropped-0.png -resize 800x480 build/resized.png
# magick build/resized.png -dither FloydSteinberg -define dither:diffusion-amount=50% -ordered-dither h4x4a -remap epaper_eink-2color.png build/dithered.png

# Screenshot the element
# NOTE: the css class is bound to change so we'll see how often this will happen
docker run -v $(pwd):/usr/src/app/out --rm ghcr.io/leipeleon/chrome-headless-screenshots:master https://www.zonneplan.nl/energie/dynamische-energieprijzen --width 1024 --height 2160 --filename "build/screenshot" --timezone "Europe/Amsterdam"  --element ".ifzWpS"
magick build/screenshot.png -chop 19x20 -crop 800x480 build/cropped.png
magick build/cropped-0.png -dither FloydSteinberg -define dither:diffusion-amount=50% -ordered-dither h4x4a -remap epaper_eink-2color.png build/dithered.png

magick build/dithered.png -monochrome -colors 2 -depth 1 -strip png:build/diffused.png
magick build/dithered.png -monochrome -colors 2 -depth 1 -strip bmp3:build/diffused.bmp
