#!/usr/bin/env bash

mkdir build
# get screenshot
docker run -v $(pwd):/usr/src/app/out --rm ghcr.io/leipeleon/chrome-headless-screenshots:master https://www.zonneplan.nl/energie/dynamische-energieprijzen --height 2160 --filename "build/screenshot"
# -> screenshot.png

# imagemagick
# magick screenshot.png -chop 390x400 -crop 1135x681 cropped1.png
magick build/screenshot.png -chop 390x520 -crop 1135x681 build/cropped1.png
# scale down
magick build/cropped1-0.png -resize 800x480 build/resized.png

magick build/resized.png -dither FloydSteinberg -define dither:diffusion-amount=85% -remap epaper_eink-2color.png build/diffused.png
