#!/usr/bin/env bash

# gnuplot  <<COMMAND
# set term png size 800,460
# set output "out.png"
# set boxwidth 0.5
# set style line 1 lc rgb "black"
# set style fill solid
# set xtics font ",10"
# plot "data.dat"  using 1:3:xtic(2) with boxes ls 1 notitle
# COMMAND

gnuplot << COMMAND
set term png size 800,460
set output "build/out.png"

set key autotitle columnhead
unset key

set title "`head -1 build/hours.dat`"

set nokey
set border 1+2
set boxwidth 0.8
set style fill solid
set xtics font ",10"

set xtics nomirror
set ytics nomirror

# set yrange [0:7]
set grid y
# set ylabel "Price €"

plot "build/hours.dat" using 0:2:3:xtic(1) with boxes lc rgb var
COMMAND
